services:
  - type: web
    name: bancosst-server
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server/index.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
